version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [ "./main", "--storage=postgres" ]
    environment:
      DB_HOST: db 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  memory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # 8081 на хосте, 8080 в контейнере
    command: [ "./main", "--storage=memory" ]
    environment:
      JWT_SECRET: ${JWT_SECRET}
      APP_PORT: 8081
    restart: always

volumes:
  postgres-data:
