// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID         string     `json:"id"`
	PostID     string     `json:"postID"`
	ParentID   *string    `json:"parentID,omitempty"`
	Content    string     `json:"content"`
	AuthorID   string     `json:"authorID"`
	CreatedAt  string     `json:"createdAt"`
	HasReplies bool       `json:"hasReplies"`
	Children   []*Comment `json:"children"`
}

type CommentConnection struct {
	Items      []*Comment `json:"items"`
	HasMore    bool       `json:"hasMore"`
	NextOffset int        `json:"nextOffset"`
}

type Mutation struct {
}

type Post struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Content          string             `json:"content"`
	CommentsDisabled bool               `json:"commentsDisabled"`
	AuthorID         string             `json:"authorID"`
	Comments         *CommentConnection `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
